"""Add User

Revision ID: 19b69859cb60
Revises: 8c5b0d6d90d0
Create Date: 2026-03-02 09:31:18.790616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b69859cb60'
down_revision = '8c5b0d6d90d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_item', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
